export const ADD_BREADCRUMB = 'ADD_BREADCRUMB'
export const REMOVE_BREADCRUMB = 'REMOVE_BREADCRUMB'
export const CLEAR_BREADCRUMBS = 'CLEAR_BREADCRUMBS'

export const SET_NETWORKS = 'SET_NETWORKS'
export const SET_CONSENSUS_TYPES = 'SET_CONSENSUS_TYPES'
